/**
 * Text-based logos OCR can actually read.
 * Symbol-only marks (Nike swoosh without "NIKE") still need the manual mask tool.
 */
export const BRAND_WATCHLIST: string[] = [
  // Eyewear
  'ray-ban',
  'rayban',
  'oakley',
  'persol',
  'maui jim',
  'carrera',
  'police',
  'gentle monster',
  'vogue',
  'polaroid',

  // Footwear — athletic
  'nike',
  'adidas',
  'puma',
  'reebok',
  'new balance',
  'asics',
  'converse',
  'vans',
  'jordan',
  'yeezy',
  'skechers',
  'sketchers',
  'fila',
  'under armour',
  'hoka',
  'salomon',
  'on running',
  'brooks',
  'mizuno',
  'kappa',
  'lotto',
  'umbro',

  // Footwear — casual / outdoor
  'timberland',
  'dr martens',
  'doc martens',
  'clarks',
  'crocs',
  'birkenstock',
  'ugg',
  'steve madden',
  'aldo',
  'nine west',
  'caterpillar',
  'columbia',
  'merrell',
  'the north face',
  'bata',
  'servis',
  'ndure',

  // Footwear — luxury / designer
  'jimmy choo',
  'manolo blahnik',
  'christian louboutin',
  'louboutin',
  'alexander mcqueen',
  'golden goose',
  'common projects',
  'off white',
  'valentino',
  'ferragamo',
  'salvatore ferragamo',

  // Fashion houses common on glasses + shoes
  'gucci',
  'prada',
  'chanel',
  'dior',
  'versace',
  'fendi',
  'burberry',
  'balenciaga',
  'armani',
  'giorgio armani',
  'emporio armani',
  'tom ford',
  'celine',
  'givenchy',
  'loewe',
  'bottega veneta',
  'saint laurent',
  'ysl',
  'louis vuitton',
  'hermes',
  'hermès',
  'michael kors',
  'coach',
  'guess',
  'lacoste',
  'ralph lauren',
  'hugo boss',
  'moschino',
  'max mara',
  'tiffany',
  'dolce gabbana',

  // Watches (still appear in this pipeline)
  'rolex',
  'cartier',
  'omega',
  'tag heuer',
  'seiko',
  'casio',
  'chenxi',
];
